### ISSUE TITLE
Settings\Woopoly Features and Meta List - current status

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#151]
This issue is a reference note to answer questions about the Settings and any outstanding issues.

## Features
- [x] **Fields Locker**	Fields locker makes it easy for user to know which field to translate and which to ignore: working as of 0.26
- [x] **Emails**	Use order language whenever WooCommerce sends order emails: working in 0.26, improved in 0.30 release candidate with more options and more email types covered
- [x] **Reports**	Enable reports language filtering and combining: implemented: if turned off, shows all results, if turned on, use language filter to filter results (not sure this is working 100% correct)
- [x] **Coupons Sync**	Apply coupons rules for product and its translations: if On, Usage Restrictions by Products and Categories also apply to the translations of any selected Products and Categories:  if off then only the selected terms will be considered
- [x] **Stock Sync**	This only affects impact of basket and orders on stock.  If turned off, the Stock class is not loaded, however this alone _may not give the expected results_ since the Stock Metas are also synchronised via the Metas List, Stock Metas.  
**Note: If the Stock Sync is turn off but the Stock Metas sync is left on, then new orders will only affect stock in current language, however if the product is saved then the Stock will be synchronized for all languages again.**
- [x] **Translate Categories**	Enable categories translations: working, if turned off, categories are available in all languages 
- [x] **Translate Tags**	Enable tags translations: working, if turned off, tags are available in all languages 
- [x] **Translate Attributes**	Enable attributes translations:  turns translation on or off for all Products\Attributes
- [x] x **Translate Shipping Classes**	Enable shipping classes translations (**not supported for WooCommerce versions >= 2.6**)  [in any case these are not normally visible to the customer?]
- [ ] ? **Translation Downloader**	Download WooCommerce translations when a new polylang language is added  _(not retested, but no changes expected.  Was fixed in 0.29.1)_

Issues:

- [x] Translate Product Categories, Product Tags and Attributes are also added to Polylang Languages\Settings\Custom Taxonomies, however Hyyan settings take precedence, and individual Attributes settings under Custom taxonomies have no effect.
- [x] check variation stock synchronization fixes for WooCommerce 3.0 obey settings
- [x] Hyyan Features/Stock Sync should take precedence over detail settings?  or at least show a warning on the Settings\Features page (added warning)

### General Metas

- [x] Product-type
- [x] Virtual
- [x] Downloadable
- [x] Sku
- [x] Regular Price
- [x] Sale Price
- [x] Sale Price Dates From
- [x] Sale Price Dates To
- [ ] Downloadable Files  -  Downloads functionality not yet re-tested
- [ ] Download Limit
- [ ] Download Expiry
- [ ] Download Type
- [ ] Menu Order -- **controlled by Polylang Language, Settings, Page order** if disabled in  Polylang it will not be synchronized regardless of woo-poly setting.
- [ ] Comment Status (Enable reviews) - - **controlled by Polylang Language, Settings, Comment Status** if disabled in Polylang synchronization will be disabled regardless of woo-poly setting.
- [x] Upsell Ids
- [x] Crosssell Ids
- [x] Featured - implemented woo3 change from Meta to Taxonomy
- [ ] Thumbnail Id - **controlled by Polylang Language, Settings, Featured image** if enabled in  Polylang it will be synchronized regardless of woo-poly setting.   Not tested, this might allow the opposite, synchronise Product Featured Image but not Post/Page featured image.
- [ ] Price - _price in wp_postmeta is the actual purchase price which is may be equal to _regular_price or _sale price: storing in _price avoids an additional calculation check over _sale_price, _sale_price_dates_from, _sale_price_dates_to	within product loops etc.  It's not so clear the effect of turning on or off synchronisation for this.
- [x] Product Image Gallery
- [ ] Total Sales - not re-tested yet
- [ ] Translation Porduct Type **What does this do??**
- [x] Visibility  - implemented woo3 change from Meta to Taxonomy

### Stock Metas
See note above on Features, Stock.  Stock synchronisation can be turned off if both Features\Stock and the Stock Metas are turned off.  These options can be turned off individually but a more normal use case would be to leave them all on or all off.
- [x] - Manage Stock
- [x] - Stock
- [x] - Backorders
- [x] - Stock Status
- [x] - Sold Individually

### Attributes Metas	

- [x] Product Attributes - **pending more testing**
When this option is selected:
- Custom product attributes defined on the Product are synchronised and not translateable by editing in the secondary language version.
- global Products\Attributes are synchronized
 - if WooPoly\Features\Translate Attributes is OFF
 - if On the synchronisation uses translated term if available or blank if no term available **missing translations will break your variations**
When this option is turned off:
- no attributes are automatically copied between translations
- all attributes are editable 
- Global Select attribute terms are still synchronised, at least when used for variations
- [x] Default Attributes - in a variation product, this is the option which is pre-selected, turning this off allows different pre-selections for different languages

### Taxes Metas	

- [x] Tax Status
- [x] Tax Class
(works, should normally be left on, tax should be driven by country not by language)

### Variables Metas	
_I read there were some changes in WooCommerce 3.x - Not yet specifically retested_
But before testing what is the desirable behaviour?  What would it mean if price synchronization is off but Max/Min price synchronisation is on??  Shouldn't WooCommerce automatically calculate these values when a product is saved?

Issues:
- Variation fields locker does not respect Meta List settings:  fields such as price remain locked even when price synchronization is turned off.  (exception is Variation Description for which a specific change was added now in the woopoly woo3 release candidate)
- [ ] Min Variation Price
- [ ] Max Variation Price
- [ ] Min Price Variation Id
- [ ] Max Price Variation Id
- [ ] Min Variation Regular Price
- [ ] Max Variation Regular Price
- [ ] Min Regular Price Variation Id
- [ ] Max Regular Price Variation Id
- [ ] Min Variation Sale Price
- [ ] Max Variation Sale Price
- [ ] Min Sale Price Variation Id
- [ ] Max Sale Price Variation Id

**Comment by Jon007** [comment]
Above long post is intended to become documentation page.

## Priority fixes:
- [ ] **#148 Visibility and Featured Product**
- [ ] #72 **Variable Product attributes missing translations**
- [ ] #127 **Text attributes** Ideally allow choice of synchronization or translation on a per-attribute basis.  Else auto-fill translations by synchronization (provided by default by #72).


## Fix by improved documentation/warnings on Settings Pages
- [ ] **Stock Synchronization** If: changing Feature Setting please also change related Metas settings
- [ ] **Price** If disabling price synchronisation 
- [ ] **Menu Order, Comment Status, Thumbnail ID** - add warnings and advise use of Polylang settings

## Lower priority, awaiting volunteers:
- [ ] **SKU** #73 
- [ ] Auto-fill term translations on categories (fill with a synchronization, user can later edit or delete it?)

**Comment by Jon007** [comment]
Close - substantially implemented in version 1.0
Wiki documentation pages added at:
[https://github.com/hyyan/woo-poly-integration/wiki/Settings---Features]
[https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas]
supersede the notes on this issue
